import Foundation
import Testing
@testable import MailTransportMailCore
import MailCore
import MailTransport
import OtegamiCore

/// Task #193: unit tests for `MailCoreIMAPSession.envelope(from:fetchedAt:)`
/// at the actual MailCore2 boundary — constructing `MCOIMAPMessage`/
/// `MCOMessageHeader` objects directly (no dev mailstack/real IMAP needed,
/// same reasoning as `MessageBuilderTests` in this same target) to reproduce
/// exactly the object shape MailCore2 hands back for a message whose
/// `Date:` header failed to parse: a header whose `.date` got stamped with
/// the fetch-time sentinel (see `EnvelopeDateSentinel`'s doc comment) while
/// `.receivedDate` (IMAP INTERNALDATE) correctly reflects the message's real
/// age.
extension MailCoreLocalSuite {
    @Suite("envelope(from:fetchedAt:) sentinel-date handling")
    struct EnvelopeSentinelDateMappingTests {
        /// `MCOMessageHeader` (the Swift-native MailCore2 port this project's
        /// `MailCore` product wraps) has no plain `init()` — only
        /// `init(mailCoreObject:)` (internal plumbing) and `init(data:)`
        /// (parses raw RFC 822 header bytes, same as `MessageBuilderTests` in
        /// this same target already uses). Parsing a minimal real header first,
        /// then overwriting `.date`/`.receivedDate`/`.messageID` directly,
        /// reproduces exactly the object shape a real IMAP `FETCH` response
        /// produces without needing a live server.
        private func makeHeader() -> MCOMessageHeader {
            MCOMessageHeader(data: Data("Subject: Test\r\n\r\n".utf8))
        }

        private func makeMessage(uid: UInt32, headerDate: Date, receivedDate: Date, messageID: String) -> MCOIMAPMessage {
            let message = MCOIMAPMessage()
            message.uid = uid
            let header = makeHeader()
            header.date = headerDate
            header.receivedDate = receivedDate
            header.messageID = messageID
            message.header = header
            return message
        }

        @Test("a header date stamped at fetch time, with a genuinely old internalDate, is dropped in favor of nil (falls back to internalDate)")
        func sentinelDateIsDropped() {
            let fetchedAt = Date(timeIntervalSince1970: 1_770_000_000)
            let tenYearsAgo = fetchedAt.addingTimeInterval(-10 * 365 * 24 * 60 * 60)
            let message = makeMessage(uid: 1, headerDate: fetchedAt, receivedDate: tenYearsAgo, messageID: "abc@x")

            let envelope = MailCoreIMAPSession.envelope(from: message, fetchedAt: fetchedAt)

            #expect(envelope.date == nil)
            #expect(envelope.internalDate == tenYearsAgo)
        }

        @Test("a genuinely fresh message (date and internalDate both close to fetchedAt) keeps its real date")
        func genuinelyFreshDateIsKept() {
            let fetchedAt = Date(timeIntervalSince1970: 1_770_000_000)
            let justArrived = fetchedAt.addingTimeInterval(-5)
            let message = makeMessage(uid: 2, headerDate: justArrived, receivedDate: justArrived, messageID: "def@x")

            let envelope = MailCoreIMAPSession.envelope(from: message, fetchedAt: fetchedAt)

            #expect(envelope.date == justArrived)
            #expect(envelope.internalDate == justArrived)
        }

        @Test("a legitimately old message, fetched long after, keeps its real date")
        func legitimatelyOldDateFarFromFetchIsKept() {
            let fetchedAt = Date(timeIntervalSince1970: 1_770_000_000)
            let longAgo = fetchedAt.addingTimeInterval(-30 * 24 * 60 * 60)
            let message = makeMessage(uid: 3, headerDate: longAgo, receivedDate: longAgo, messageID: "ghi@x")

            let envelope = MailCoreIMAPSession.envelope(from: message, fetchedAt: fetchedAt)

            #expect(envelope.date == longAgo)
            #expect(envelope.internalDate == longAgo)
        }

        @Test("a Message-ID that MailCore2 fabricated (no Message-ID header on the wire) is reported as nil, not the fabricated value")
        func autoGeneratedMessageIDIsDroppedToNil() {
            // `MCOMessageHeader` has no public setter for its auto-generated
            // flag directly, but `init(data:)` (via `makeHeader()`) still runs
            // MailCore2's default constructor internally before parsing the
            // header text — same `init(true, true)` MailCore2 always runs on
            // construction. Since `makeHeader()`'s fixture text has no
            // `Message-ID:` line, nothing overwrites the auto-generated one,
            // reproducing exactly this shape without needing IMAP/a live
            // server.
            let fetchedAt = Date(timeIntervalSince1970: 1_770_000_000)
            let header = makeHeader()
            #expect(header.isMessageIDAutoGenerated)
            let message = MCOIMAPMessage()
            message.uid = 4
            message.header = header

            let envelope = MailCoreIMAPSession.envelope(from: message, fetchedAt: fetchedAt)

            #expect(envelope.messageId == nil)
        }

        @Test("an explicitly-set Message-ID is reported as-is, not dropped")
        func explicitMessageIDIsKept() {
            let fetchedAt = Date(timeIntervalSince1970: 1_770_000_000)
            let header = makeHeader()
            header.messageID = "real-id@otegami.test"
            #expect(!header.isMessageIDAutoGenerated)
            let message = MCOIMAPMessage()
            message.uid = 5
            message.header = header

            let envelope = MailCoreIMAPSession.envelope(from: message, fetchedAt: fetchedAt)

            #expect(envelope.messageId == "<real-id@otegami.test>")
        }
    }
}
