#!/usr/bin/env bash
# Xcode Cloud post-clone hook (Task #49, docs/xcode-cloud.md). Xcode Cloud
# looks for this script in a `ci_scripts` directory that sits next to the
# .xcodeproj/.xcworkspace the workflow builds — for this repo that's
# apps/Otegami, not the repo root, since Otegami.xcodeproj is generated
# there by XcodeGen (git-ignored, apps/Otegami/project.yml is the source of
# truth). Runs once, right after Xcode Cloud clones the repository and
# before it resolves the Xcode project at all — which is exactly why the
# `xcodegen generate` below has to happen here: without it, there is no
# .xcodeproj yet for Xcode Cloud to build.
#
# Local dry run (no real secrets committed anywhere — this only exercises
# the script's own logic against a throwaway config):
#   OTEGAMI_DEVELOPMENT_TEAM=TESTTEAM1234 \
#   OTEGAMI_BUNDLE_ID=com.example.otegami.citest \
#     apps/Otegami/ci_scripts/ci_post_clone.sh
set -euo pipefail

# ---------------------------------------------------------------------------
# Locate the repo root.
#
# Xcode Cloud sets CI_PRIMARY_REPOSITORY_PATH to the cloned repository's
# path (e.g. /Volumes/workspace/repository) — prefer it when present. Fall
# back to a path computed from this script's own location so the script
# also works for a local dry run or a differently-mounted CI checkout.
# ---------------------------------------------------------------------------
if [ -n "${CI_PRIMARY_REPOSITORY_PATH:-}" ]; then
  REPO_ROOT="$CI_PRIMARY_REPOSITORY_PATH"
else
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
fi
cd "$REPO_ROOT"

APP_DIR="apps/Otegami"
LOCAL_XCCONFIG="$APP_DIR/Config/Local.xcconfig"

echo "==> ci_post_clone: repo root = $REPO_ROOT"

# ---------------------------------------------------------------------------
# XcodeGen — Xcode Cloud's macOS images ship with Homebrew but not
# XcodeGen. `--quiet` keeps the log focused; a bare `brew install` here is
# idempotent (brew no-ops if already installed), matching the same command
# .github/workflows/ci-app.yml already runs for the same reason.
# ---------------------------------------------------------------------------
if ! command -v xcodegen >/dev/null 2>&1; then
  echo "==> ci_post_clone: installing xcodegen"
  brew install xcodegen
fi

# ---------------------------------------------------------------------------
# Config/Local.xcconfig — the git-ignored, per-builder override file
# (Config/Local.xcconfig.sample) that Config/Signing.xcconfig #include?s
# last, so any value set here wins over the committed defaults in
# Config/Shared.xcconfig/Signing.xcconfig without editing either. Xcode
# Cloud has no such file (it's not in git), so this generates one from
# workflow environment variables — the same mechanism a human developer
# uses locally, just filled in by CI instead of by hand. Every var is
# optional: an unset one simply omits that line, leaving the committed
# default (empty DEVELOPMENT_TEAM/GOOGLE_OAUTH_CLIENT_ID, NO
# OTEGAMI_MAIL_CLIENT_ENTITLEMENT, default OTEGAMI_BUNDLE_ID) in effect —
# so a workflow that only sets OTEGAMI_DEVELOPMENT_TEAM (the minimum
# needed for a signed archive) still produces a working, if
# Gmail/mail-client-disabled, build.
#
# `OTEGAMI_*`-prefixed *workflow* variable names are deliberately distinct
# from the xcconfig keys they map to (e.g. OTEGAMI_GOOGLE_CLIENT_ID here vs
# GOOGLE_OAUTH_CLIENT_ID in the xcconfig) so they're unambiguous in the
# Xcode Cloud environment-variables UI, which lists variables across every
# workflow with no per-app namespacing of its own.
echo "==> ci_post_clone: writing $LOCAL_XCCONFIG"
{
  echo "// Generated by ci_scripts/ci_post_clone.sh — do not edit by hand."
  echo "// See Config/Local.xcconfig.sample for what each key does."
  [ -n "${OTEGAMI_DEVELOPMENT_TEAM:-}" ] && echo "DEVELOPMENT_TEAM = ${OTEGAMI_DEVELOPMENT_TEAM}"
  [ -n "${OTEGAMI_BUNDLE_ID:-}" ] && echo "OTEGAMI_BUNDLE_ID = ${OTEGAMI_BUNDLE_ID}"
  [ -n "${OTEGAMI_GOOGLE_CLIENT_ID:-}" ] && echo "GOOGLE_OAUTH_CLIENT_ID = ${OTEGAMI_GOOGLE_CLIENT_ID}"
  [ -n "${OTEGAMI_MAIL_CLIENT_ENTITLEMENT:-}" ] && echo "OTEGAMI_MAIL_CLIENT_ENTITLEMENT = ${OTEGAMI_MAIL_CLIENT_ENTITLEMENT}"
  # CI_BUILD_NUMBER is an Xcode Cloud built-in (monotonically increasing
  # per workflow) — feeding it into CURRENT_PROJECT_VERSION here is what
  # project.yml's `CFBundleVersion: $(CURRENT_PROJECT_VERSION)` (both the
  # Otegami and NotificationService targets — see their doc comments)
  # actually picks up at build time. Without this, every TestFlight
  # upload would carry the same committed CURRENT_PROJECT_VERSION (1)
  # from Config/Shared.xcconfig and App Store Connect would reject the
  # second and subsequent uploads of the same MARKETING_VERSION as a
  # duplicate build number.
  [ -n "${CI_BUILD_NUMBER:-}" ] && echo "CURRENT_PROJECT_VERSION = ${CI_BUILD_NUMBER}"
} > "$LOCAL_XCCONFIG"

# ---------------------------------------------------------------------------
# Generate the Xcode project. Must run after Local.xcconfig above so a
# fresh `xcodegen generate` sees it — in practice XcodeGen doesn't read
# xcconfig values at generate time for anything this script sets (they're
# all consumed as `$(...)` macros at *build* time, see project.yml's doc
# comments), so the ordering isn't load-bearing today, but keeping
# Local.xcconfig-before-generate avoids relying on that being true forever.
# ---------------------------------------------------------------------------
echo "==> ci_post_clone: xcodegen generate"
(cd "$APP_DIR" && xcodegen generate)

echo "==> ci_post_clone: done"
