import Foundation

/// Task #193 (実機バグ「10年以上前に送った送信済みメールが、6時間前くらいの
/// 日付で受信箱に表示される」): detects MailCore2's "couldn't parse a real
/// `Date:` header" sentinel.
///
/// MailCore2's `MessageHeader` default constructor unconditionally stamps a
/// freshly-created header's date with `time(NULL)` — confirmed against the
/// pinned revision's `src/core/abstract/MCMessageHeader.cpp`:
/// `MessageHeader::MessageHeader()` calls `init(true, true)`, which sets
/// `mDate = time(NULL)` (and `mReceivedDate` the same way) *before* the
/// envelope is ever parsed. `importIMAPEnvelope` only overwrites `mDate`
/// when the server's `ENVELOPE` response actually carries a parseable
/// `env_date` (see that same file, ~line 787: both the `mailimf_date_time_
/// parse`/`mailimap_hack_date_time_parse` branches only call `setDate`
/// inside their `if (r == ...NO_ERROR)` success arm). A message whose
/// `Date:` header is missing or malformed keeps that construction-time
/// "now" stamp forever — indistinguishable at this layer from a genuinely
/// fresh message's real `Date:` header, since `MCOMessageHeader.date`
/// always returns a concrete `NSDate`, never `nil`, regardless of whether
/// the envelope actually had one. Unlike the analogous Message-ID case
/// (`MessageHeader.isMessageIDAutoGenerated`), MailCore2 exposes no direct
/// "was this actually parsed" accessor for `date`.
///
/// The distinguishing signal instead: IMAP's `INTERNALDATE` (this app's
/// `internalDate`, mirroring `MessageHeader.receivedDate`) is assigned
/// server-side at `APPEND`/delivery time and is *always* overwritten
/// unconditionally by `importIMAPInternalDate` whenever the server returns
/// the `INTERNALDATE` FETCH attribute — which this app always requests
/// (`MailCoreIMAPSession`'s `kind` constants always include `.internalDate`).
/// So the sentinel's signature is: `date` sits suspiciously close to
/// `referenceTime` (see the two call sites for what each one passes — the
/// actual fetch moment going forward, or the row's `updatedAt` as the best
/// available approximation for data already stored) *while* `internalDate`
/// disagrees with `date` by more than that same tolerance. Both conditions
/// matter together: a genuinely-just-arrived message also has `date` close
/// to `referenceTime`, but its `internalDate` (arrival time) agrees with
/// `date` too in that case, so it's correctly left alone.
public enum EnvelopeDateSentinel {
    /// How close `date` must sit to `referenceTime` — and how far it must
    /// sit from `internalDate` — to be flagged. Generous on purpose: a
    /// multi-batch `fetchEnvelopes` call, or (for the repair path) the
    /// delay between a corrupted row being written and this check running
    /// against its `updatedAt`, can take a while, but a *legitimate*
    /// `Date:`/`INTERNALDATE` pairing that happens to straddle the exact
    /// sync moment by sheer coincidence is nowhere near as common in
    /// practice as this bug.
    public static let defaultTolerance: TimeInterval = 60 * 60

    /// `true` when `date` looks like MailCore2's construction-time sentinel
    /// rather than a genuinely parsed `Date:` header.
    public static func isSuspicious(
        date: Date,
        internalDate: Date,
        referenceTime: Date,
        tolerance: TimeInterval = defaultTolerance
    ) -> Bool {
        abs(date.timeIntervalSince(referenceTime)) <= tolerance
            && abs(date.timeIntervalSince(internalDate)) > tolerance
    }

    /// `nil` when `date` is flagged as suspicious (letting callers fall
    /// back to `internalDate` themselves — this codebase's established
    /// `date ?? internalDate` idiom, used consistently by `ThreadAssigner`/
    /// `MessageQuery`/`ThreadQuery`/the message-list UI), `date` unchanged
    /// otherwise.
    public static func reconciledDate(
        date: Date,
        internalDate: Date,
        referenceTime: Date,
        tolerance: TimeInterval = defaultTolerance
    ) -> Date? {
        isSuspicious(date: date, internalDate: internalDate, referenceTime: referenceTime, tolerance: tolerance)
            ? nil
            : date
    }
}
