package cryptox

import (
	"encoding/base64"
	"testing"
)

func TestRoundTrip(t *testing.T) {
	key := make([]byte, 32)
	c, err := New(key)
	if err != nil {
		t.Fatal(err)
	}
	ciphertext, err := c.Encrypt("s3cr3t-app-password")
	if err != nil {
		t.Fatal(err)
	}
	plaintext, err := c.Decrypt(ciphertext)
	if err != nil {
		t.Fatal(err)
	}
	if plaintext != "s3cr3t-app-password" {
		t.Fatalf("got %q", plaintext)
	}
}

func TestUTF8RoundTrip(t *testing.T) {
	key := make([]byte, 32)
	for i := range key {
		key[i] = byte(i)
	}
	c, err := New(key)
	if err != nil {
		t.Fatal(err)
	}
	ciphertext, err := c.Encrypt("パスワード🔑")
	if err != nil {
		t.Fatal(err)
	}
	plaintext, err := c.Decrypt(ciphertext)
	if err != nil {
		t.Fatal(err)
	}
	if plaintext != "パスワード🔑" {
		t.Fatalf("got %q", plaintext)
	}
}

func TestNonceIsFresh(t *testing.T) {
	key := make([]byte, 32)
	c, _ := New(key)
	first, _ := c.Encrypt("same-password")
	second, _ := c.Encrypt("same-password")
	if base64.StdEncoding.EncodeToString(first) == base64.StdEncoding.EncodeToString(second) {
		t.Fatal("expected different ciphertexts for repeated encryption (nonce reuse)")
	}
}

func TestWrongKeyFails(t *testing.T) {
	key1 := make([]byte, 32)
	key2 := make([]byte, 32)
	key2[0] = 1
	c1, _ := New(key1)
	c2, _ := New(key2)
	ciphertext, _ := c1.Encrypt("s3cr3t")
	if _, err := c2.Decrypt(ciphertext); err == nil {
		t.Fatal("expected decrypt with wrong key to fail")
	}
}

func TestTamperedCiphertextFails(t *testing.T) {
	key := make([]byte, 32)
	c, _ := New(key)
	ciphertext, _ := c.Encrypt("s3cr3t")
	ciphertext[0] ^= 0xFF
	if _, err := c.Decrypt(ciphertext); err == nil {
		t.Fatal("expected decrypt of tampered ciphertext to fail")
	}
}

func TestNewFromBase64KeyRejectsWrongLength(t *testing.T) {
	shortKey := base64.StdEncoding.EncodeToString(make([]byte, 16))
	if _, err := NewFromBase64Key(shortKey); err == nil {
		t.Fatal("expected error for short key")
	}
}

func TestNewFromBase64KeyRejectsInvalidBase64(t *testing.T) {
	if _, err := NewFromBase64Key("not valid base64!!"); err == nil {
		t.Fatal("expected error for invalid base64")
	}
}

func TestGenerateBase64KeyWorks(t *testing.T) {
	generated, err := GenerateBase64Key()
	if err != nil {
		t.Fatal(err)
	}
	c, err := NewFromBase64Key(generated)
	if err != nil {
		t.Fatal(err)
	}
	ciphertext, err := c.Encrypt("round-trip")
	if err != nil {
		t.Fatal(err)
	}
	plaintext, err := c.Decrypt(ciphertext)
	if err != nil {
		t.Fatal(err)
	}
	if plaintext != "round-trip" {
		t.Fatalf("got %q", plaintext)
	}
}

// --- Cross-implementation compatibility fixtures ---
//
// Generated by a standalone Swift program using swift-crypto 3.15.1 (the
// exact version pinned in server/otegami-relay/Package.resolved) calling
// AES.GCM.seal(_:using:).combined — the identical code path
// CredentialCrypto.encrypt(_:) uses. These are NOT round-tripped through
// this Go implementation; they verify this Go implementation can decrypt
// bytes a real Swift relay actually produced and would have persisted to
// SQLite, which is the whole point of Task #180's compatibility
// requirement: an existing production database's `watch.encryptedSecret`
// column must decrypt under this new binary with zero migration.
func TestDecryptsSwiftEncryptedFixtureASCII(t *testing.T) {
	keyB64 := "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
	combinedB64 := "VP9OQ6surTn0txwmV5TAa45whEc/jp1phpcN4IcpH3x8sOhNQjPInzRzFpb9iuw="
	wantPlaintext := "s3cr3t-app-password"

	c, err := NewFromBase64Key(keyB64)
	if err != nil {
		t.Fatal(err)
	}
	combined, err := base64.StdEncoding.DecodeString(combinedB64)
	if err != nil {
		t.Fatal(err)
	}
	got, err := c.Decrypt(combined)
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}
	if got != wantPlaintext {
		t.Fatalf("got %q, want %q", got, wantPlaintext)
	}
}

func TestDecryptsSwiftEncryptedFixtureUTF8(t *testing.T) {
	keyB64 := "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
	combinedB64 := "DzvkYFkeEgNcsldT/dGObXfV4lQoYdQS73hda02iSHuxrABr9wHSszdaBU36P0g="
	wantPlaintext := "パスワード🔑"

	c, err := NewFromBase64Key(keyB64)
	if err != nil {
		t.Fatal(err)
	}
	combined, err := base64.StdEncoding.DecodeString(combinedB64)
	if err != nil {
		t.Fatal(err)
	}
	got, err := c.Decrypt(combined)
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}
	if got != wantPlaintext {
		t.Fatalf("got %q, want %q", got, wantPlaintext)
	}
}

func TestDecryptsSwiftEncryptedFixtureOAuthRefreshToken(t *testing.T) {
	keyB64 := "5TU4asN5V3EJUXUxI9nwQnWaKfJ3a3oEFTEGDJRUDyc="
	combinedB64 := "8lbsANHUxSxrhvoPjVTBNR+Dufe2sM6oknQjLyvUleiUg+PaYvJZGqaMiVVgAUQyKyV+YEL448HPhpV8jctw0Lv3wD9JjsQHHDSzOUL0Dck/"
	wantPlaintext := "1//0gAbCdEfGhIjKlMnOpQrStUvWxYz-refresh-token-example"

	c, err := NewFromBase64Key(keyB64)
	if err != nil {
		t.Fatal(err)
	}
	combined, err := base64.StdEncoding.DecodeString(combinedB64)
	if err != nil {
		t.Fatal(err)
	}
	got, err := c.Decrypt(combined)
	if err != nil {
		t.Fatalf("decrypt failed: %v", err)
	}
	if got != wantPlaintext {
		t.Fatalf("got %q, want %q", got, wantPlaintext)
	}
}

func TestDecryptRejectsNonUTF8Plaintext(t *testing.T) {
	// Swift's CredentialCrypto.decrypt fails when the decrypted bytes are
	// not valid UTF-8 (String(data:encoding:) returns nil) — encrypt raw
	// invalid-UTF-8 bytes with the same primitives and require Decrypt to
	// reject them the same way.
	key := make([]byte, 32)
	c, err := New(key)
	if err != nil {
		t.Fatal(err)
	}
	aead, err := c.aead()
	if err != nil {
		t.Fatal(err)
	}
	nonce := make([]byte, nonceSize)
	combined := aead.Seal(nonce, nonce, []byte{0xFF, 0xFE, 0x80}, nil)
	if _, err := c.Decrypt(combined); err == nil {
		t.Fatal("expected non-UTF-8 plaintext to be rejected")
	}
}
