import Foundation
import MailCore
import MailTransport
import OtegamiCore

/// Renders a `ComposeDraft` into a full RFC 822 message via `MCOMessageBuilder`
/// (M5). Plain text only — HTML composition and attachments land in M8+.
/// Japanese subject/body encoding is left entirely to MailCore2's own MIME
/// writer (RFC 2047 encoded-words for the subject, a suitable
/// `Content-Transfer-Encoding` for the body), the same "let MailCore2 handle
/// charset conversion" approach `MailCoreIMAPSession.fetchBody` already
/// takes on the receiving side.
///
/// A free function rather than a type instantiated per call: `MCOMessageBuilder`
/// carries no state worth keeping between builds, and the app injects
/// `MailCoreMessageBuilder.build` into `SyncEngine.OpQueueProcessor` as a
/// plain closure (`@Sendable (ComposeDraft) -> BuiltMessage`) — the same
/// "app wires the real MailCore2-backed implementation, `SyncEngine` only
/// knows the `MailTransport`-level shape" pattern already used for
/// `IMAPSessionProtocol`/`SMTPSessionProtocol` session factories.
public enum MailCoreMessageBuilder {
    public static func build(_ draft: ComposeDraft) -> BuiltMessage {
        let builder = MCOMessageBuilder()
        builder.header.from = mcoAddress(draft.from)
        builder.header.to = draft.to.map(mcoAddress)
        if !draft.cc.isEmpty {
            builder.header.cc = draft.cc.map(mcoAddress)
        }
        if !draft.bcc.isEmpty {
            builder.header.bcc = draft.bcc.map(mcoAddress)
        }
        builder.header.subject = draft.subject
        if let inReplyTo = draft.inReplyTo {
            builder.header.inReplyTo = [inReplyTo]
        }
        if !draft.references.isEmpty {
            builder.header.references = draft.references
        }
        builder.textBody = draft.plainTextBody

        // Generated explicitly (rather than relying on MCOMessageBuilder's
        // own `isMessageIDAutoGenerated` fallback) so the value returned
        // here is guaranteed to be exactly what ends up in the rendered
        // `data()` — `OpQueueProcessor`/tests need a `Message-ID` they can
        // rely on without re-parsing the RFC 822 bytes just to recover it.
        let messageId = "<\(UUID().uuidString)@otegami.local>"
        builder.header.messageID = messageId

        return BuiltMessage(data: builder.data() ?? Data(), messageId: messageId)
    }

    private static func mcoAddress(_ address: EmailAddress) -> MCOAddress {
        if let name = address.name, !name.isEmpty {
            // swiftlint:disable:next force_unwrap
            return MCOAddress(displayName: name, mailbox: address.address)!
        }
        // swiftlint:disable:next force_unwrap
        return MCOAddress(mailbox: address.address)!
    }
}
