import Foundation
import MailCore
import MailTransport
import OtegamiCore

/// Renders a `ComposeDraft` into a full RFC 822 message via `MCOMessageBuilder`
/// (M5). Plain text body only — HTML composition is still out of scope;
/// file attachments (M8) are supported via `ComposeDraft.attachments`.
/// Japanese subject/body encoding is left entirely to MailCore2's own MIME
/// writer (RFC 2047 encoded-words for the subject, a suitable
/// `Content-Transfer-Encoding` for the body), the same "let MailCore2 handle
/// charset conversion" approach `MailCoreIMAPSession.fetchBody` already
/// takes on the receiving side.
///
/// A free function rather than a type instantiated per call: `MCOMessageBuilder`
/// carries no state worth keeping between builds, and the app injects
/// `MailCoreMessageBuilder.build` into `SyncEngine.OpQueueProcessor` as a
/// plain closure (`@Sendable (ComposeDraft) -> BuiltMessage`) — the same
/// "app wires the real MailCore2-backed implementation, `SyncEngine` only
/// knows the `MailTransport`-level shape" pattern already used for
/// `IMAPSessionProtocol`/`SMTPSessionProtocol` session factories.
public enum MailCoreMessageBuilder {
    public static func build(_ draft: ComposeDraft) -> BuiltMessage {
        let builder = MCOMessageBuilder()
        builder.header.from = mcoAddress(draft.from)
        builder.header.to = draft.to.map(mcoAddress)
        if !draft.cc.isEmpty {
            builder.header.cc = draft.cc.map(mcoAddress)
        }
        if !draft.bcc.isEmpty {
            builder.header.bcc = draft.bcc.map(mcoAddress)
        }
        builder.header.subject = draft.subject
        if let inReplyTo = draft.inReplyTo {
            builder.header.inReplyTo = [inReplyTo]
        }
        if !draft.references.isEmpty {
            builder.header.references = draft.references
        }
        builder.textBody = draft.plainTextBody

        // M8: plain (non-inline) attachments only — a reply never carries
        // the original's inline `cid:` images forward either (plan: "返信時
        // の元添付は引き継がない"), and `ComposerView` never builds an HTML
        // body of its own to reference a `cid:` from, so `relatedAttachments`
        // (MCOMessageBuilder's inline-image list) stays unused here.
        if !draft.attachments.isEmpty {
            builder.attachments = draft.attachments.map(mcoAttachment)
        }

        // Generated explicitly (rather than relying on MCOMessageBuilder's
        // own `isMessageIDAutoGenerated` fallback) so the value returned
        // here is guaranteed to be exactly what ends up in the rendered
        // `data()` — `OpQueueProcessor`/tests need a `Message-ID` they can
        // rely on without re-parsing the RFC 822 bytes just to recover it.
        let messageId = "<\(UUID().uuidString)@otegami.local>"
        builder.header.messageID = messageId

        return BuiltMessage(data: builder.data() ?? Data(), messageId: messageId)
    }

    /// `MCOAttachment(data:filename:)` infers a MIME type from the filename
    /// extension internally, but setting `.mimeType` explicitly afterward
    /// makes the wire content type exactly what `ComposeAttachment.mimeType`
    /// says (the UTType-derived guess `ComposerView` already made when the
    /// file was picked) rather than relying on a second, possibly different
    /// guess made again here from the filename alone.
    private static func mcoAttachment(_ attachment: ComposeAttachment) -> MCOAttachment {
        let mco = MCOAttachment(data: attachment.data, filename: attachment.filename)
        mco.mimeType = attachment.mimeType
        // Task #66: `setContentTypeParameterValue(_:name:)` appends a
        // genuinely separate `Content-Type` parameter (mailcore2's
        // `content_type_parameters_from_attachment`/`mime_from_attachment`
        // read these back and hand them to libetpan's `mailmime_content`
        // verbatim) — unlike folding `"; method=REPLY"` into `mimeType`
        // itself, which would risk the whole string being quoted as one
        // opaque atom instead of parsed as `type/subtype` plus a parameter.
        //
        // The call below passes `(value: name, name: value)` — swapped
        // from what the method's own parameter labels suggest — to work
        // around a confirmed bug in this pinned mailcore2 revision's Swift
        // port: `AbstractPart.setContentTypeParameter(name:value:)`'s core
        // (C++) signature is `(name, value)`, and the Objective-C binding
        // calls it in that order, but `AbstractPart.swift`'s
        // `setContentTypeParameterValue(_ value:name:)` calls
        // `nativeInstance.setContentTypeParameter(value, name)` — i.e. the
        // two arguments reversed. Confirmed empirically (not just by
        // reading the vendored source) by `MessageBuilderTests
        // .calendarReplyContentTypeParameterRoundTrips`: calling this with
        // the "obvious" `(value, name: name)` order produced a wire
        // `Content-Type` of `text/calendar; REPLY="method"` instead of
        // `text/calendar; method=REPLY`. Swapping here is the narrowest
        // fix — patching the vendored dependency itself would need to
        // survive every future `mailcore2` version bump.
        for (name, value) in attachment.contentTypeParameters {
            mco.setContentTypeParameterValue(name, name: value)
        }
        return mco
    }

    private static func mcoAddress(_ address: EmailAddress) -> MCOAddress {
        if let name = address.name, !name.isEmpty {
            // swiftlint:disable:next force_unwrap
            return MCOAddress(displayName: name, mailbox: address.address)!
        }
        // swiftlint:disable:next force_unwrap
        return MCOAddress(mailbox: address.address)!
    }
}
